Standard error codes.

diff --git a/sr b/sr
--- a/sr
+++ b/sr
@@ -6,9 +6,16 @@
 # please refer to https://docs.wildlife.systems, or for more information on
 # the project itself, please refer to https://wildlife.systems.
 
+# Return codes
+#
+# Further information on WildlifeSystems standard reurn codes can be found
+# at https://docs.wildlife.systems/return-codes.html
+# 0 - Success
+# 2 - no arguments provided
+
 if [[ $# -eq 0 ]]; then
   echo "No arguments supplied"
-  exit 1
+  exit 2
 fi
 
 SCRIPT=$1
